### ISSUE TITLE
ctx is untyped..

### ISSUE THREAD

**Issue by kristiandupont** [maloguertin/msw-trpc#2] opened 2023-02-03 15:24 UTC
Your library is exactly what I was hoping to find, thank you!

The one issue I have right now is that the `ctx` parameter is untyped. This is surprising to me as it appears that it should be correctly typed via the `ExtractProcedureHandler` type. 

<img width="454" alt="image" src="https://user-images.githubusercontent.com/847742/216640026-98ab2bab-06ef-4377-998a-c21d97f59ee4.png">

My `mswTrpc` instance is pretty straight forward:
```typescript
const mswTrpc = createTRPCMsw<AppRouter>({
  transformer: { input: superjson, output: superjson },
});
```

..what am I missing?

**Comment by maloguertin** [comment] 2023-02-03 15:26
Hi kristian, I'll try to get around to debugging your use case today!

**Comment by kristiandupont** [comment] 2023-02-03 15:31
That's awesome, thank you. I am happy to help as well, I just wanted to make sure I wasn't missing something simple first.

**Comment by maloguertin** [comment] 2023-02-03 22:44
Could you give me a reproducible example of a trpc router

**Comment by kristiandupont** [comment] 2023-02-06 12:07
With this AppRouter definition:

```typescript
const appRouter = router({
  user: publicProcedure
    .input(Number)
    .output(Object)
    .query((req) => ALL_USERS.find((user) => req.input === user.id)),
});
```

I get the same result. Let me know if I should try and set up a repository for you.

**Comment by maloguertin** [comment] 2023-02-06 13:38
Here's my setup:

```
import createTRPCMsw from '../src/createTRPCMsw'
import { initTRPC } from '@trpc/server'
import superjson from 'superjson'

const t = initTRPC.create({ transformer: superjson })
export interface User {
  id: Number
  name: string
}
const ALL_USERS: User[] = [
  {
    id: 1,
    name: 'KATT',
  },
]
const appRouter = t.router({
  user: t.procedure
    .input(Number)
    .output(Object)
    .query(req => ALL_USERS.find(user => req.input === user.id)),
})
export type AppRouter = typeof appRouter

export const mswTrpc = createTRPCMsw<AppRouter>({ transformer: { input: superjson, output: superjson } })

mswTrpc.user.query((req, res, ctx) => {
  ctx.data
})
```

![image](https://user-images.githubusercontent.com/6407064/216985753-1b8032a4-2d66-42f1-9002-f07114c300d0.png)

If you can give me a repo it would help :)

**Comment by kristiandupont** [comment] 2023-02-06 13:43
Interesting. Well it's good to know that it *should* work -- in that case I will first try and check that I didn't do something stupid. I'll report back here, either with the fix or with a reproduction repo :-)

**Comment by CUexter** [comment] 2023-02-14 22:21
I am having the same problem here

**Comment by maloguertin** [comment] 2023-02-14 23:01
> I am having the same problem here

Hi! Could you fill this template to help me narrow down the bug:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Versions**
typescript: vX.Y.Z
tRPC: vX.Y.Z
msw: vX.Y.Z

**Comment by CUexter** [comment] 2023-02-15 06:43
> 

what would be the type of ctx in this example ?

**Comment by CUexter** [comment] 2023-02-15 07:16
I tried using create-t3-stack, and it uses [inner and outer context from the trpc docs](https://trpc.io/docs/context#inner-and-outer-context ), I wonder if this is the reason why

**Comment by CUexter** [comment] 2023-02-15 07:28
I tried copy and paste your example and it doesn't work, can you tell me the version of msw  you are using ?

**Comment by CUexter** [comment] 2023-02-15 07:44
wait reinstalling msw seems to solve the issue, not sure why

**Comment by kristiandupont** [comment] 2023-02-15 08:20
@CUexter sadly that doesn't seem to solve it for me. Which version of TS are you using?

**Comment by CUexter** [comment] 2023-02-15 09:01
@kristiandupont 4.9.4, try installing the old version of msw from 0.49.3 ?

**Comment by kristiandupont** [comment] 2023-02-15 09:08
That worked, thank you!!

**Comment by CUexter** [comment] 2023-02-15 10:52
i tried updating it back and it still works. what package manager are u using

**Comment by kristiandupont** [comment] 2023-02-15 11:55
Weird indeed. I haven't tried updating after this, but I think I will leave it for now. I am using Yarn.

**Comment by maloguertin** [comment] 2023-02-15 13:20
So it seems like the issue might be with latest version of MSW?

**Comment by kristiandupont** [comment] 2023-02-15 13:37
Well I tried first upgrading to the latest version which didn't do anything. I then downgraded to exactly version 0.49.3 as per CUexter's suggestion, and then it worked.

**Comment by CUexter** [comment] 2023-02-15 13:39
But I upgrade it back up and it does seem to work as well idk

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CUexter** [comment] 2023-02-17 21:13
@maloguertin I am sorry, it doesn't work for 1.0.1. I was wrong.

#6 is also solved after downgrade

**Comment by maloguertin** [comment] 2023-04-25 20:09
If you can give me a repo with the issue I'll try fixing it.

**Comment by maloguertin** [comment] 2023-04-28 19:01
should be fixed with https://github.com/maloguertin/msw-trpc/releases/tag/v1.3.0

**Closed by maloguertin** 2023-04-28 19:01 UTC
Labels: bug
